[[redirects]]
from="https://leitura.jnaraujo.com/*"
to="https://leiturabilidade.site/:splat"
status=301
force=true

[[redirects]]
from="https://www.leitura.jnaraujo.com/*"
to="https://leiturabilidade.site/:splat"
status=301
force=true

[[redirects]]
from="https://leiturabilidade.jnaraujo.com/*"
to="https://leiturabilidade.site/:splat"
status=301
force=true

[[redirects]]
from="https://www.leiturabilidade.jnaraujo.com/*"
to="https://leiturabilidade.site/:splat"
status=301
force=true