[functions]

  [functions._ipx]
  node_bundler = "nft"

  [functions.___netlify-handler]
  included_files = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.production.local",
    "./public/locales/**",
    "./next-i18next.config.js",
    ".next/server/**",
    ".next/serverless/**",
    ".next/*.json",
    ".next/BUILD_ID",
    ".next/static/chunks/webpack-middleware*.js",
    "!.next/server/**/*.js.nft.json",
    "!.next/server/**/*.map",
    "!**/node_modules/@next/swc*/**/*",
    "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
    "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/compiled/webpack/bundle4.js",
    "!node_modules/next/dist/compiled/webpack/bundle5.js",
    "!node_modules/sharp/**/*"
  ]
  external_node_modules = []
  node_bundler = "nft"

  [functions.___netlify-odb-handler]
  included_files = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.production.local",
    "./public/locales/**",
    "./next-i18next.config.js",
    ".next/server/**",
    ".next/serverless/**",
    ".next/*.json",
    ".next/BUILD_ID",
    ".next/static/chunks/webpack-middleware*.js",
    "!.next/server/**/*.js.nft.json",
    "!.next/server/**/*.map",
    "!**/node_modules/@next/swc*/**/*",
    "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
    "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/compiled/webpack/bundle4.js",
    "!node_modules/next/dist/compiled/webpack/bundle5.js",
    "!node_modules/sharp/**/*"
  ]
  external_node_modules = []
  node_bundler = "nft"

  [functions."_api_*"]
  included_files = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.production.local",
    "./public/locales/**",
    "./next-i18next.config.js",
    ".next/server/**",
    ".next/serverless/**",
    ".next/*.json",
    ".next/BUILD_ID",
    ".next/static/chunks/webpack-middleware*.js",
    "!.next/server/**/*.js.nft.json",
    "!.next/server/**/*.map",
    "!**/node_modules/@next/swc*/**/*",
    "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
    "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/compiled/webpack/bundle4.js",
    "!node_modules/next/dist/compiled/webpack/bundle5.js",
    "!node_modules/sharp/**/*"
  ]
  external_node_modules = []
  node_bundler = "nft"

[build]
command = "yarn next build"
publish = ".next"

  [build.environment]
  NEXT_PRIVATE_TARGET = "server"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200

[[redirects]]
from = "/_next/image*"
to = "/_ipx/w_:width,q_:quality/:url"
status = 301

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/builders/_ipx"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/app.png"
to = "/app.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/fallback-XZNvnxUpRO6RcZVtmIUxH.js"
to = "/fallback-XZNvnxUpRO6RcZVtmIUxH.js"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/favicon.ico"
to = "/favicon.ico"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/manifest.json"
to = "/manifest.json"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/icons/144.png"
to = "/icons/144.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/icons/192.png"
to = "/icons/192.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/icons/48.png"
to = "/icons/48.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/icons/500.png"
to = "/icons/500.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/icons/72.png"
to = "/icons/72.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/icons/96.png"
to = "/icons/96.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/ui/home_mobile.png"
to = "/ui/home_mobile.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/ui/home_pc.png"
to = "/ui/home_pc.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200
force = true

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/_next/data/InumgS6ZrTk1ZHsvnsLto/blog.json"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200
force = true

[[redirects]]
from = "/blog"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200
force = true

[[redirects]]
from = "/_next/data/InumgS6ZrTk1ZHsvnsLto/blog/3-dicas-para-deixar-seu-texto-mais-simples.json"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200
force = true

[[redirects]]
from = "/blog/3-dicas-para-deixar-seu-texto-mais-simples"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200
force = true

[[redirects]]
from = "/_next/data/InumgS6ZrTk1ZHsvnsLto/blog/como-deixar-meu-texto-mais-facil-de-ser-lido.json"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200
force = true

[[redirects]]
from = "/blog/como-deixar-meu-texto-mais-facil-de-ser-lido"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200
force = true

[[redirects]]
from = "/_next/data/InumgS6ZrTk1ZHsvnsLto/index.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_next/data/InumgS6ZrTk1ZHsvnsLto/editor.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/editor"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_next/data/InumgS6ZrTk1ZHsvnsLto/blog/:slug.json"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200

[[redirects]]
from = "/blog/:slug"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200

[context]

  [context.dev]

    [context.dev.environment]
    NEXT_PRIVATE_TARGET = "server"

    [context.dev.functions]

      [context.dev.functions._ipx]
      node_bundler = "nft"

      [context.dev.functions.___netlify-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "!node_modules/sharp/**/*"
      ]
      external_node_modules = []
      node_bundler = "nft"

      [context.dev.functions.___netlify-odb-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "!node_modules/sharp/**/*"
      ]
      external_node_modules = []
      node_bundler = "nft"

      [context.dev.functions."_api_*"]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "!node_modules/sharp/**/*"
      ]
      external_node_modules = []
      node_bundler = "nft"

    [context.dev.build]

      [context.dev.build.environment]
      NEXT_PRIVATE_TARGET = "server"

  [context.main]

    [context.main.environment]
    NEXT_PRIVATE_TARGET = "server"

    [context.main.functions]

      [context.main.functions._ipx]
      node_bundler = "nft"

      [context.main.functions.___netlify-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "!node_modules/sharp/**/*"
      ]
      external_node_modules = []
      node_bundler = "nft"

      [context.main.functions.___netlify-odb-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "!node_modules/sharp/**/*"
      ]
      external_node_modules = []
      node_bundler = "nft"

      [context.main.functions."_api_*"]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "!node_modules/sharp/**/*"
      ]
      external_node_modules = []
      node_bundler = "nft"

    [context.main.build]

      [context.main.build.environment]
      NEXT_PRIVATE_TARGET = "server"