[[redirects]]
from="https://leiturabilidade.site/*"
to="https://leitura.jnaraujo.com/:splat"
status=301
force=true

[[redirects]]
from="https://www.leiturabilidade.site/*"
to="https://leitura.jnaraujo.com/:splat"
status=301
force=true

[[redirects]]
from="https://leiturabilidade.jnaraujo.com/*"
to="https://leitura.jnaraujo.com/:splat"
status=301
force=true

[[redirects]]
from="https://www.leiturabilidade.jnaraujo.com/*"
to="https://leitura.jnaraujo.com/:splat"
status=301
force=true
