import Navbar from "@/components/Navbar"
import "./globals.css"
import { Inter, Merriweather } from "next/font/google"

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" })
const merriweather = Merriweather({
  subsets: ["latin"],
  variable: "--font-merriweather",
  weight: ["400", "700"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className={`${merriweather.variable} ${inter.variable}`}>
      <body className="bg-zinc-50 text-zinc-900">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
